export const REQUEST_TODOLIST = 'REQUEST_TODOLIST';
export const REQUEST_TODOLIST_SUCCEEDED = 'REQUEST_TODOLIST_SUCCEEDED';
export const REQUEST_TODOLIST_FAILED = 'REQUEST_TODOLIST_FAILED';
export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_TODO_FAILED = 'DELETE_TODO_FAILED';
export const DELETE_TODO_SUCCEEDED = 'DELETE_TODO_SUCCEEDED';